### ISSUE TITLE
TransactionContextMiddleware seems unnecessary

### ISSUE THREAD

**Issue by NilsMoller** [liberation-data/drivine#107]
The website, in the sections about [Transactions](https://drivine.org/guide/#/transactions?id=transactions), mentions to register the `TransactionContextMiddleware` in `AppModule`. I am using GraphQL and Fastify (in Nest 8). Fastify has no native middleware support which could be why I'm getting a very vague error from `Middie` (a middleware package for Fastify).  

This would be a problem, but it seems the `@Transactional` decorator works fine. It shows a message in the console saying a transaction has started at the right moment in the code, and it cleans it up properly as well. What is the TransactionContextMiddleware supposed to do? Could it be depricated and the website not updated?

**Comment by jasperblues** [comment]
Hey @NilsMoller !! Happy new year!

Are you using Fastify via NestJS or directly? 

`TrasnactionContextMiddleWare` does this: 

```typescript
 return inDrivineContext().run(async () => {
            this.transactionContext.databaseRegistry = this.databaseRegistry;
            return Promise.resolve(next());
        });
```

And what that does is just run a method inside a NodeJS `AsyncLocalStorage` context. This feature of NodeJS allows us to store information in call-chain (similar to a ThreadLocal in a traditional web server). 

We also use it for the integration test feature where a transaction is started and rolled back when the test completes. 

For transactions to work as expected, you need to set that up. I believe if you use Fastify via NestJS it will 'just work' in most cases, as their middleware is portable between the two platforms. 

I'm guessing that's what you're doing. (I planned to publish NestJS support in a separate module, so people can use drivine anywhere, but never had time for that).

**Comment by NilsMoller** [comment]
Thank you! Same to you!

I use Fastify with NestJS.

> For transactions to work as expected, you need to set that up. I believe if you use Fastify via NestJS it will 'just work' in most cases, as their middleware is portable between the two platforms.

When I try to add the `TransactionContextMiddleware` in `AppModule`, it gives me the error below. Without it, the `@Transactional` decorator works fine. I have not checked the integration tests, but I presume they will not work as you said. Do you have any recommendations/have you seen this before? Otherwise I will have to start messing around with custom middleware to either wrap yours or write the same code.

When running with this:
```TypeScript
export default class AppModule implements NestModule {
  public configure(consumer: MiddlewareConsumer): any {
    consumer.apply(TransactionContextMiddleware).forRoutes("**/**");
  }
}
```
it gives this error:
```
E:\Git_repos\content-experience-center-api\node_modules\middie\node_modules\path-to-regexp\src\index.ts:157
    throw new TypeError(`Unexpected ${nextType} at ${index}, expected ${type}`);
          ^
TypeError: Unexpected MODIFIER at 1, expected END
    at mustConsume (E:\Git_repos\content-experience-center-api\node_modules\middie\node_modules\path-to-regexp\src\index.ts:157:11)
    at parse (E:\Git_repos\content-experience-center-api\node_modules\middie\node_modules\path-to-regexp\src\index.ts:227:5)
    at stringToRegexp (E:\Git_repos\content-experience-center-api\node_modules\middie\node_modules\path-to-regexp\src\index.ts:493:25)
    at pathToRegexp (E:\Git_repos\content-experience-center-api\node_modules\middie\node_modules\path-to-regexp\src\index.ts:620:10)
    at Object.use (E:\Git_repos\content-experience-center-api\node_modules\middie\engine.js:23:16)
    at Object.use (E:\Git_repos\content-experience-center-api\node_modules\middie\index.js:26:21)
    at E:\Git_repos\content-experience-center-api\node_modules\@nestjs\platform-fastify\adapters\fastify-adapter.js:254:27
    at MiddlewareModule.registerHandler (E:\Git_repos\content-experience-center-api\node_modules\@nestjs\core\middleware\middleware-module.js:154:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jasperblues** [comment]
I don't know why it would throw that error. What do the NestJS docs say about using middleware with Fastify? 

If it works without the middleware, then it means that the fastify endpoints are already running inside an async local storage context. This is plausible. 

For tests you can just use the approach in the docs/instructions - on the website.

**Comment by NilsMoller** [comment]
I was going to reply with a "Middleware is abstracted by Nest, which wraps any middleware using `NestMiddleware`, meaning there is no difference between express and fastify." I went to double check the docs, and it turns out there is [one difference](https://docs.nestjs.com/middleware#route-wildcards):
> The `fastify` package uses the latest version of the `path-to-regexp` package, which no longer supports wildcard asterisks `*`. Instead, you must use parameters (e.g., `(.*)`, `:splat*`).  

Apparently the error I posted previously is what happens when the `.forRoutes` argument is invalid.  

Thank you for your help once again!

For completeness sake, this is my current `AppModule` and it is working:
```TypeScript
export default class AppModule implements NestModule {
  public configure(consumer: MiddlewareConsumer): any {
    consumer.apply(TransactionContextMiddleware).forRoutes("(.*)");
  }
}
```

**Comment by jasperblues** [comment]
Glad that you got it solved @NilsMoller !!
