### ISSUE TITLE
Error: variable does not exist - Apache AGE

### ISSUE THREAD

**Issue by avifatal** [liberation-data/drivine#109]
Hi,
Im trying a simple query with binded variables on Apache AGE:
```
        const res = await this.persistenceManager.execute(
            new QuerySpecification() .withStatement( `MERGE  (a:account {origin_id: 1})  SET n.web_profile = $1 ` )
                .bind(['some profile']),
        );
```
or like that:
```
        const res = await this.persistenceManager.execute(
            new QuerySpecification() .withStatement( `MERGE  (a:account {origin_id: 1})  SET n.web_profile = $profile ` )
                .bind({profile: 'some profile'}),
        );
```

I am getting the error:
```
Error: variable does not exist
    at Function.withRootCause (/home/avi/work/xplor-backend/node_modules/@liberation-data/src/DrivineError.ts:8:16)
    at NonTransactionalPersistenceManager.query (/home/avi/work/xplor-backend/node_modules/@liberation-data/src/manager/NonTransactionalPersistenceManager.ts:31:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at NonTransactionalPersistenceManager.execute (/home/avi/work/xplor-backend/node_modules/@liberation-data/src/manager/NonTransactionalPersistenceManager.ts:36:9)
```
Thanks

**Comment by jasperblues** [comment]
I haven't updated Drivine yet to support Apache AGE. We need to create an adapter for the driver, in the same way that was done for Neo4j and for AgensGraph. 

It should be a fairly simple task.

**Comment by jasperblues** [comment]
If you are using AgensGraph, I recommend to first try the sample app: https://github.com/liberation-data/drivine-inspiration

There are instructions to get started. The main issue some folks have trouble with is configuring .env file for driver. 

Can you confirm you're able to run all the examples in the sample? If you can let's take it from there.

**Comment by pawankukreja01** [comment]
In your first example, you are binding an array of strings to $1. However, in your query, you are using n.web_profile instead of $1. You should replace n.web_profile with $1 in your query.

In your second example, you are binding an object with a key profile and value 'some profile' to $profile. However, in your query, you are using n.web_profile instead of $profile. You should replace n.web_profile with $profile in your query.

**Comment by jasperblues** [comment]
Closing this @avifatal as it looks like @pawankukreja01 helped you. _(Thanks @pawankukreja01 )_
