### ISSUE TITLE
Turn off logging while unit testing

### ISSUE THREAD

**Issue by alexgarbarev** [liberation-data/drivine#12]
Hi.
I'm running unit tests, I was unable to turn off logging.

Here is similar issue: https://github.com/nestjs/nest/issues/3246

I found that for regular run we can do the following:
```
  const app = await NestFactory.create(AppModule, {
    logger: ['error', 'warn'],
  });
```
but for unit tests, we cannot do so. 

Maybe it's worth adding a logger to option to `DrivineModuleOptions` ?

**Comment by jasperblues** [comment]
Verified that drivine correctly honors log_level.

**Comment by myflowpl** [comment]
@jasperblues "Verified that drivine correctly honors log_level" what does it mean ?
how we should turn of logging for tests vs production vs development ?
how you doing it in your application?

**Comment by jasperblues** [comment]
https://docs.nestjs.com/techniques/logger

^-- Just using NestJS facilities @myflowpl for test vs production and other logging concerns @myflowpl. I showed @alexgarbarev and I believe it Is working well for him now too.

**Comment by alexgarbarev** [comment]
For tests, I'm using EmptyLogger
```
import { LoggerService } from '@nestjs/common';
export class EmptyLogger implements LoggerService {
  log(message: string): any {}
  error(message: string, trace: string): any {}
  warn(message: string): any {}
  debug(message: string): any {}
  verbose(message: string): any {}
}
```
Then in test:
```
const app = await Test.createTestingModule(module).compile();
app.useLogger(new EmptyLogger());
```

**Comment by myflowpl** [comment]
@jasperblues I'v tried it all 

Nest recommends to use Dependency Injection for injecting the  logger, in order to overwrite it in unit tests, but Drivine is not using the DI for it:

https://github.com/liberation-data/drivine/blob/master/src/logger/StatementLogger.ts
```ts
import { Logger } from '@nestjs/common';
import { QuerySpecification } from '@/query/QuerySpecification';

export class StatementLogger {
    private logger = new Logger(StatementLogger.name);// <<<--- should be injected

    constructor(readonly sessionId: string) {}

    log(query: QuerySpecification<any>, hrStart: [number, number]): void {
        const hrEnd = process.hrtime(hrStart);
        const uSec = Math.round(hrEnd[1] / 1000);
        this.logger.verbose({
            ...query,
            sessionId: this.sessionId,
            elapsed: `${uSec} µsec`
        });
    }
}
```
Nest docs recomends something like this:

```ts
constructor(private myLogger: MyLogger) {
    this.myLogger.setContext('CatsService');
  }
```
That's why I can't disable it for tests

I'v tried the static method to disable logLevel, and it is not working:

```ts
import { Logger } from '@nestjs/common';
Logger.overrideLogger(['error'])
```

Thanks for your help.

Drivine is so cool, good work !!!

**Comment by myflowpl** [comment]
ok, it looks like `Drivine` should have `@nestjs/common` and `@nestjs/core` as `peerDependencies`

now it is placed in `dependencies`:

```json
"dependencies": {
        "@nestjs/common": "^6.8.3",
        "@nestjs/core": "^6.8.3",
        "@nestjs/platform-express": "^6.8.3",
}
```

so if you use divine in project where you have the nestjs version 6,  then the static method will work

in my case I'm using nestjs version 7, so static method `Logger.overrideLogger(['error'])` will not work, be course drivine and my project will receive different references

**Comment by xv-jasper-b** [comment]
> @jasperblues do you use nestjs v7 or v6 in your applications ??

Up until now NestJS 6, but I prefer to stay on the latest versions, and recommend that in general. 

If we set it up so that it is easy for all users that is preference. 

Second preference is to make it easy/default for 7 and possible for 6. 

Do you have a suggestion?

**Comment by jasperblues** [comment]
> @jasperblues do you use nestjs v7 or v6 in your applications ??

Up until now NestJS 6, but I prefer to stay on the latest versions, and recommend that in general. 

If we set it up so that it is easy for all users that is preference. 

Second preference is to make it easy/default for 7 and possible for 6. 

Do you have a suggestion?

**Comment by myflowpl** [comment]
@jasperblues  yes, quickest fix would be to move the `nestjs` inside `package.json`  from `dependencies` section to `peerDependencies` section.

Even without updating the nest version to 7, but I recommend to update the nest version to latest and run all the tests to see if it's working

In this case, all projects using v6 will work with no problems

and all projects using v7 will also work, but only with smal warning during `npm install` saying that drivine pear deps are wrong, but it will work without problems on run time.

`package.json` NOW

```json
    "peerDependencies": {},
    "dependencies": {
        "@liberation-data/agensgraph": "^0.1.0-rc",
        "@nestjs/common": "^6.8.3",
        "@nestjs/core": "^6.8.3",
        "@nestjs/platform-express": "^6.8.3",
        "class-transformer": "^0.2.3",
       ...
    },
```

AFTER FIX


```json
    "peerDependencies": {
        "@nestjs/common": "^6.8.3",
        "@nestjs/core": "^6.8.3",
        "@nestjs/platform-express": "^6.8.3"
    },
    "dependencies": {
        "@liberation-data/agensgraph": "^0.1.0-rc",
        "class-transformer": "^0.2.3",
       ...
    },
```

**Comment by jasperblues** [comment]
Alright, let's do that. Will do asap. 

Or if you're so inclined, feel free to send a PR!

**Comment by myflowpl** [comment]
@jasperblues yes, I can do PR for this one, and I also found some other issues so I'll add them and if possible also do PR.

I'll do it in next 2 days, while I'm developing my app i'll also test the solution.

May be you can reopen this issue or should I post new one ?

**Comment by jasperblues** [comment]
Thank you Piotr!

**Comment by jasperblues** [comment]
@myflowpl Btw, as you're among the first contributors, along with Khoak, Aleksey and Jeet, you're welcome to be featured on the website. If you'd like that pls send photo and few sentence bio to jasper@liberation-data.com

**Comment by myflowpl** [comment]
@jasperblues thanks Jasper, that is very nice of you, lets do that after my PR's will be merged ;) 

I'm just migrating from OrientDB to Neo4j, and Drivine draw my attention while I was looking for solution in Node.js, so far it's so cool, and only found minor bugs.

Today I'm trying to do my first deployment do testing servers with Neo4j+drivine, and hope to have time tomorrow to do some work on drivine

Good work :)

**Comment by geoshak** [comment]
I have been struggling with this for several hours now on a very simple jest unit test, and I can't believe how massively frustrating it is.

Tried mocking, spying on console, global console, replacing the property, mocking, spying on Logger, Logger.overrideLogger, nothing works.

I guess I might be venting out a bit, and I might find a solution in the next minute.
But this should not be so hard. Feels like a massive time waste. Makes me sad to the core.
Will report back if I find any meaningful/minimally elegant solution.

**Comment by jasperblues** [comment]
Did you set the DRIVINE_LOG_LEVEL? Here's an example if you're configuring
via an env file:
https://github.com/liberation-data/drivine-inspiration/blob/master/.env.sample

Drivine has its own logger so you can turn it off and on. The issues you're
reading are stale threads in relation to why people wanted that.

**Comment by geoshak** [comment]
hey @jasperblues I had to vent off but in my frustration I didn't notice that the link I followed on `NestJS` repo actually took me to `drivine`. My issue was with NestJS not drivine. Thanks for the response anyway!!
