### ISSUE TITLE
Graceful shutdown & connections

### ISSUE THREAD

**Issue by alexgarbarev** [liberation-data/drivine#13]
I found that we need to close all db connections manually sometimes. Great example is unit tests:

1) In scenario, when we setting up a postgres/agensgraph database before running tests, and then stopping it once all tests are finished, we need to close database connection before stopping the database. Otherwise an error arise: `Connection terminated unexpectedly`

2) even if we are not setting a database for tests, jest will warn `Jest did not exit one second after the test run has completed.`

In order to close connection, we need to do:
In `AgensGraphConnectionProvider.ts`
we need to run `await this.pool.end()`

I think we might add a method to `ConnectionProvider` interface to end all connections immediately and a helper static method to `ConnectionProviderBuilder` to close all connections in registry.

In terms of NestJS, I think should also hook on `onApplicationShutdown` and close all connections there.

**Comment by jasperblues** [comment]
I can see that it will be useful, bearing in mind that if you use `inTestContext().run` it will remind  you to set a connection pool IDLE_TIMEOUT short enough for Jest to shut down cleanly.

**Comment by jasperblues** [comment]
Fixed in Drivine 1.1.0
