### ISSUE TITLE
[How to] : Use this with aws lambda

### ISSUE THREAD

**Issue by grizzly-monkey** [liberation-data/drivine#18]
I am pretty new to graph db and node ... so might be silly question.
However would be great how I can use this with aws lambdas. 
Do I need nestjs to work with  drivine  ?
Is it possible to publish a sample aws lambda with drivine ?

**Comment by xv-jasper-b** [comment]
Don't necessarily need NestJS, however: 

* As yet there isn't an example of using without NestJS. 
* Some features are NestJS specific.
* Dependencies haven't been split into separate npms - at the moment, the main one will pull in NestJS, at the moment, even if it is not used.

**Comment by jasperblues** [comment]
Don't necessarily need NestJS, however: 

* As yet there isn't an example of using without NestJS. 
* Some features are NestJS specific.
* Dependencies haven't been split into separate npms - at the moment, the main one will pull in NestJS, at the moment, even if it is not used.

**Comment by grizzly-monkey** [comment]
Thanks @jasperblues  ... do you plan to package deps accordingly in near future ? I am trying one to build for aws hope it works out . :)

**Comment by jasperblues** [comment]
I could do it when time permits, however have you thought about using NestJS from Lambda? 

https://github.com/rdlabo/serverless-nestjs

**Comment by grizzly-monkey** [comment]
I read that however i feel its an over head..  most of the things are taken care by API Gw.. and the package size gets added.

**Comment by grizzly-monkey** [comment]
@jasperblues  I am trying to get the Drivine running in aws lambda without nestjs.

For that have using a global function like this.
I am not so good with node world and learning as I age... so forgive for my grave mistakes in case.


```function init(): Promise<any> {
    return inDrivineContext().run(async () => {
        DbRegistry.buildOrResolveFromEnv();
    });
}
```



```@Service()
export class BomRepositoryImpl implements BomRepository {
    private logger = getLogger(BomRepositoryImpl.name);
    private persistenceManager: PersistenceManager;

    constructor() {
        this.persistenceManager = new TransactionalPersistenceManager(TransactionContextHolder.getInstance(),
            ServiceConfig.db.name);
    }

    @Transactional()
    async getAllBoms(id: string): Promise<Tenant> {
        this.logger.debug(`Start getting bom ${id}`);
        const spec = new QuerySpecification<Tenant>()
            .withStatement(
                `MATCH (Tenant{_id:$1}) return Tenant`
            )
            .bind([id])
            .transform(Tenant);

        return this.persistenceManager.getOne(spec);
    }
}
```

This has 2 issues which i am not able to solve 
1) the class-transformer is not able to map the values returns me always a null object.
<img width="1245" alt="Screenshot 2020-05-05 at 1 26 06 AM" src="https://user-images.githubusercontent.com/6825834/81009307-08023600-8e72-11ea-9aad-740d760e6766.png">
<img width="786" alt="Screenshot 2020-05-05 at 12 14 58 AM" src="https://user-images.githubusercontent.com/6825834/81009315-0d5f8080-8e72-11ea-82b3-e661add507e5.png">

[rec.txt](https://github.com/liberation-data/drivine/files/4577185/rec.txt)

2) When i re-run the api i get below error
```  Error --------------------------------------------------
 
  Error: No context available. ns.run() or ns.bind() must be called first.
      at Namespace.set (/opt/glabbr/code/infniti/ms/bom-service-node/node_modules/cls-hooked/context.js:36:11)
      at o.set (/opt/glabbr/code/infniti/ms/bom-service-node/.webpack/service/src/api/webpack:/src/db/transaction/TransactonContextHolder.ts:66:24)
      at o.currentTransaction (/opt/glabbr/code/infniti/ms/bom-service-node/.webpack/service/src/api/webpack:/src/db/transaction/TransactonContextHolder.ts:50:14)
      at new u (/opt/glabbr/code/infniti/ms/bom-service-node/.webpack/service/src/api/webpack:/src/db/transaction/Transaction.ts:28:28)
      at runInTransaction (/opt/glabbr/code/infniti/ms/bom-service-node/.webpack/service/src/api/webpack:/src/db/transaction/Transactional.ts:35:61)
      at n.getAllBoms (/opt/glabbr/code/infniti/ms/bom-service-node/.webpack/service/src/api/webpack:/src/db/transaction/Transactional.ts:15:20)
      at c.getAllBoms (/opt/glabbr/code/infniti/ms/bom-service-node/.webpack/service/src/api/webpack:/src/service/bom-service-impl.ts:12:19)
      at e.getBOM (/opt/glabbr/code/infniti/ms/bom-service-node/.webpack/service/src/api/webpack:/src/api/get-bom.ts:47:35)```

**Comment by jasperblues** [comment]
Let's solve the 2nd problem first. Transactions need to be called in a Drivine context. You can do this manually or set up a middleware. Here's the NestJS middleware: 

```typescript
@Injectable()
export class TransactionContextMiddleware implements NestMiddleware {
    constructor(readonly transactionContext: TransactionContextHolder, readonly databaseRegistry: DatabaseRegistry) {}

    async use(req: express.Request, res: express.Response, next: express.NextFunction): Promise<any> {
        return inDrivineContext().run(async () => {
            this.transactionContext.databaseRegistry = this.databaseRegistry;
            return Promise.resolve(next());
        });
    }
}

```

**Comment by grizzly-monkey** [comment]
> Let's solve the 2nd problem first. Transactions need to be called in a Drivine context. You can do this manually or set up a middleware. Here's the NestJS middleware:
> 
> ```ts
> @Injectable()
> export class TransactionContextMiddleware implements NestMiddleware {
>     constructor(readonly transactionContext: TransactionContextHolder, readonly databaseRegistry: DatabaseRegistry) {}
> 
>     async use(req: express.Request, res: express.Response, next: express.NextFunction): Promise<any> {
>         return inDrivineContext().run(async () => {
>             this.transactionContext.databaseRegistry = this.databaseRegistry;
>             return Promise.resolve(next());
>         });
>     }
> }
> ```

Yes if this is what I did in first stamement.
inDrivineContext().run(async () => {
        DbRegistry.buildOrResolveFromEnv();
    });

this works for me but only once next time i hit the api again. it gives me the error.

**Comment by jasperblues** [comment]
You run your queries in context, not the setting up of drivine. 

The middleware above means that any endpoint invocation is already in context. 

Need to set up the equivalent for AWS.

**Comment by grizzly-monkey** [comment]
ok while i figure out the way for this in AWS ... can you help me with the data to class issue ?

**Comment by jasperblues** [comment]
What happens when you use `NonTransactionalPersistenceManager` ? Can you log the output without a mapper? Let's see if it is something compatible for mapping.

**Comment by grizzly-monkey** [comment]
No luck with NonTxPresistMgr

output of query before mapQueryResult 
```
[

    {
        "keys":[
            "Tenant"
        ],
        "length":1,
        "_fields":[
            {
                "identity":{
                    "low":0,
                    "high":0
                },
                "labels":[
                    "Tenant"
                ],
                "properties":{
                    "_id":"amZXSkaZsX",
                    "usr":"amZXSkaZsX",
                    "passwd":"amZXSkaZsX",
                    "uri":"neo4j://localhost:7687",
                    "dbName":"bom-service-WTGVmpb",
                    "ownerEmail":"jeet@glabbr.com"
                }
            }
        ],
        "_fieldLookup":{
            "Tenant":0
        }
    }

]
```

Output for   const results = this.mapToNative(records); before  
plainToClass(spec.transformType, results);
```
[

    {
        "Tenant":{
            "_id":"amZXSkaZsX",
            "usr":"amZXSkaZsX",
            "passwd":"amZXSkaZsX",
            "uri":"neo4j://localhost:7687",
            "dbName":"bom-service-WTGVmpb",
            "ownerEmail":"jeet@glabbr.com"
        }
    }

]

```

I think the  this.mapToNative(records) should return only 

```
[

    {
        "_id":"amZXSkaZsX",
            "usr":"amZXSkaZsX",
            "passwd":"amZXSkaZsX",
            "uri":"neo4j://localhost:7687",
            "dbName":"bom-service-WTGVmpb",
            "ownerEmail":"jeet@glabbr.com"
    }

]

```

My Tenant class
```
export class Tenant {
    _id: string;
    usr: string;
    passwd: string;
    uri: string;
    dbName: string;
    ownerEmail: string;
}
```

**Comment by jasperblues** [comment]
If it was me I would call JSON.strinfigy on the result, and then create a unit test that class plainToClass on that - to debug the mapping.

**Comment by grizzly-monkey** [comment]
Yes that what i did  called JSON.strinfigy  on result, i could understand that in current code you are mapping all the properties against the lable/key due to which the plainToClass is not working.
When i removed the key it started working.

I was trying to run the test cases however they are not working on my laptop not sure why. the change i made was 
```
           const item = {};
            for (let j = 0; j < record.keys.length; j++) {
                const key = record.keys[j];
                item[key] = toNative(record.get(j));
            }
            data[i] = item;
```
to

```
            let item = {};
            for (let j = 0; j < record.keys.length; j++) {
              //  const key = record.keys[j];
                // @ts-ignore
                item = toNative(record.get(j));
            }
            data[i] = item;
```

**Comment by jasperblues** [comment]
You should not need to change that.

**Comment by grizzly-monkey** [comment]
What do you suggest how should we fix it ?

**Comment by jasperblues** [comment]
Seems like there are two issues: 

* New to learning how Drivine works. 
* Converting to AWS Lambda, despite there being no sample/howto for this yet. 

Are you able to submit a failing test case using standard drivine (with NestJS)  ? Or if it works on standard setup, it is clear the problem is in the AWS assembly.

**Comment by grizzly-monkey** [comment]
I feel the query is not working which i have shown below is a simple query.
Not sure if it changes something specific to AWS / Nest.

```
 const spec = new QuerySpecification<Tenant>()
            .withStatement(
                `MATCH (Tenant{_id:$1}) return Tenant`
            )
            .bind([id])
            .transform(Tenant);
```

**Comment by xv-jasper-b** [comment]
Can you try: 

```
MATCH (t:Tenant{_id:$1}) with t return {t.firstPropertyOfInterest, t.secondProp, t.anotherProp}
```

**Comment by jasperblues** [comment]
Can you try: 

```
MATCH (t:Tenant{_id:$1}) with t return {
   t.firstPropertyOfInterest, 
   t.secondProp, 
   t.anotherProp
}
```

I forgot to mention that with drivine's performance goals, we pluck what we like from the results. 

_(I also forgot that it works like this, as I was working on something completely different for 10+ weeks)_

**Comment by grizzly-monkey** [comment]
Hey @jasperblues thanks , I will try this and let you ASAP.

**Comment by jasperblues** [comment]
It will surely work. Sorry that this wasn't obvious to me earlier (it should have been) - I got a bit sidetracked in that we were also converting for NestJS-less and Lambda. 

We can also easily support mapping without having to push the results into a JS object compatible structure in the query. Just will require a few considerations.
