### ISSUE TITLE
Use index.ts to export public API

### ISSUE THREAD

**Issue by myflowpl** [liberation-data/drivine#19]
It's common practice to use one `index.ts` file to re-export the public API of the libraries, so we can hide inner structure of the files from the outside world.

so instead of
```ts
import { Transactional } from '@liberation-data/drivine/transaction/Transactional';
import { PersistenceManager } from '@liberation-data/drivine/manager/PersistenceManager';
```
we will have this
```ts
import { Transactional, PersistenceManager   } from '@liberation-data/drivine';
```

Is there any reason Drivine is not doing this ?

**Comment by jasperblues** [comment]
The only reason is we haven't set it up yet, but arguably we should have when we released official 1.x.x stream.
