### ISSUE TITLE
Notes not created when testing with transaction rollback: true

### ISSUE THREAD

**Issue by myflowpl** [liberation-data/drivine#25]
If you try to create node and run your test with automatic rollback, the nodes are not created and there is no errors

```ts
RunWithDrivine({
    transaction:{rollback: true}
})
```

Just created PR with tests in `HealthRepository.spec.ts` to illustrate the problem
```ts

    it('should create new user', async () => {
        const data = {id: 2, name: 'Jasper'};
        // create user
        const user = await repo.create(data);
        expect(user).toMatchObject(data) // <--- node created OK
        // find created user
        const user2 = await repo.findById(data.id); // <--- but here the node is 404 Not Found
        expect(user2).toMatchObject(data)
  
      });
```

This was working with `drivine@1.1.6` commit `06cf4d5 Update Neo4j driver to support v4` 

and the bug was introduced with commit `Use neo4j connection scheme, rather than bolt.` or more likely with `Use reactive neo4j api.`

@jasperblues  can you help with the sollution ? Just wasted 2 days to find out where was the problem and don't have energy to look deep down into it

**Comment by jasperblues** [comment]
Thanks for reporting @myflowpl. It should be fixed in Drivine 1.2.1. 

I would appreciate if you could verify, so that the issue can be closed.

**Comment by myflowpl** [comment]
@jasperblues It's working, thanks for quick fix 😃

**Comment by jasperblues** [comment]
You're welcome. Thanks for choosing (and contributing to) Drivine.
