### ISSUE TITLE
Remove hard import dependency from class-transformer

### ISSUE THREAD

**Issue by nartc** [liberation-data/drivine#29]
Currently, `drivine` lists `class-transformer` as `peerDependencies`. However, https://github.com/liberation-data/drivine/blob/master/src/query/QuerySpecification.ts#L1 uses a hard-import from `class-transformer` making `class-transformer` a required dependency.

**Comment by jasperblues** [comment]
Hey Chau, thanks a lot for reporting. Fixed and published in v1.2.3 - I created a local mirror of the simple type that we need from class-transformer, that way we can leave it as a peer dependency. 

Closing without waiting for your verification as this is 99.9% likely to be resolved.

**Comment by nartc** [comment]
Thanks @jasperblues . It worked.
