### ISSUE TITLE
Async Hooks leak memory when used with Jest

### ISSUE THREAD

**Issue by jasperblues** [liberation-data/drivine#35]
Not a problem in production, since we have one namespace for the lifecycle of the app, but excessive memory consumed for integration tests:

From @alexgarbarev: 

> My investigations regarding memory leak. (this is all with `--runInBand --logHeapUsage`)

> 1) All test suits (files) runs on same process (same PID), that means that real HEAP is shared across all test files. 
> That means, if we leak something in test 1, it will remain there.

> 2) Though, we have same PID and hence HEAP, each test suite (file) ran in isolation (jest feature). That means if you store variable to global in file 1, you won't be able to access it in file 2. 
> Practical consequence: we cannot store something to global or `static` variable in file 1, and then reuse it in file 2. I guess it requires modules independently.

> 3) By localizing problem, commeting bare-minimal code line by line, I found that `DatabaseRegistry` and `TransactionContextHolder` might leak, as they store shared instance. > > That instance might leak after end of test file if not tear it down. I have added simple tear down method, but it didn't help. See next.

> 4) Although we can tear down all our static variables at the end of test suite, `cls-hooked` is leaking. Once you create `cls.createNamespace(namespaceName)` it allocates a lot of space (like 10mb) and it persists forever. There is no API clean that. I have checked the implementation here: https://github.com/Jeff-Lewis/cls-hooked/blob/master/context.js and it looks like `destory` method doesn't do anything with created async_hook. It just zeroing reference to own object. I've seen in Chrome memory profiler that AsyncHook objects are created again and again without releasing. So we cannot fix that, and we cannot reuse same async hooks, as jest isolate each test suite. 

> So far, I found the only solution is to build own implementation of async hook. There is brand new API, called AsyncLocalStorage, which ships with node since v13.10.0: https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage
It looks pretty clear, but bare minimal. Requires some code in order to store more than "pseudo thread id"

**Comment by alexgarbarev** [comment]
Some new insides, corrections:

1. I was not correct when said it takes 10mb. Plain async_hook takes only 2mb. If you try to store something in namespace, that won't be freed, so you can waste 10mb or more.

2. Speaking of `AsyncLocalStorage` I found that node v13 and v14 is not LTS yet, and many packages are not updated for these versions. It's not ready for production apps yet (and my app doesn't work with these versions). Btw there is libraries to consider: https://github.com/thorough-developer/fast-als, https://github.com/kibertoad/asynchronous-local-storage.

3. I tried to fix memory leak in cls-hooked, and it looks like I did it correctly (I would like to have authors review though..). https://github.com/alexgarbarev/cls-hooked/commit/abcf5a7d1468e50f8cf0a935d634f577317c4af6

How I tested and proved leaks / leaks fixes:
I have added 4 copies of this test cases:
```ts
import { TestClsHooked } from './test-cls-hooks';

describe('Cls Hooked', () => {


  beforeAll(() => {
    TestClsHooked.setup();
  });

  afterAll(() => {
    TestClsHooked.tearDown();
  });


  describe('Service creation works', () => {
    it('should be created', () => {
      TestClsHooked.makeTest();
    });
  });

});
```

Where TestClsHooked mimics our implementation in Drivine:
```ts
import * as cls from 'cls-hooked';
import * as Faker from 'faker'

export class TestClsHooked {
  
  static instance: TestClsHooked;

  namespace: cls.Namespace;
  namespaceName = '__test_memory_leak__';
 

  static setup(): void {
    TestClsHooked.instance = new TestClsHooked();
  }

  static tearDown(): void {
    TestClsHooked.instance.tearDown();
    TestClsHooked.instance = null;
  }

  static makeTest(): void {
    const hook = TestClsHooked.instance;
    hook.namespace.run(() => {
      hook.namespace.set('key', Faker.lorem.lines(25));
    });
  }
  
  constructor() {
    this.namespace = cls.createNamespace(this.namespaceName);
    this.namespace.createContext()
  }

  tearDown(): void {
   
    cls.destroyNamespace(this.namespaceName);
    this.namespace = null;
  }

}
```
So, we creating a namespace, setting string value for key inside that, then destorying. And that runs 4 times via ```node --expose-gc ./node_modules/.bin/jest --logHeapUsage --runInBand```.
Before my commit:
![Screenshot_20200602_200708](https://user-images.githubusercontent.com/2268687/83529788-a71b5b80-a50c-11ea-947a-6877a399ffaa.png)
After my commit:
![Screenshot_20200602_200541](https://user-images.githubusercontent.com/2268687/83529829-b39fb400-a50c-11ea-9d3e-4576ab34ae95.png)

So my next step would be fixing Drivine code directly
