### ISSUE TITLE
Cannot find module '@liberation-data/agensgraph/lib'

### ISSUE THREAD

**Issue by myflowpl** [liberation-data/drivine#46]
lets make `@liberation-data/agensgraph` optional if you use neo4j, now i have error `Cannot find module '@liberation-data/agensgraph/lib' from '../../../../node_modules/@liberation-data/drivine/connection/AgensGraphConnectionProvider.js'` and I'm forced to install it

**Comment by jasperblues** [comment]
This is a duplicate of #30

**Comment by myflowpl** [comment]
ah, sorry, I was in a rush and didn't check... we don't need 2 issues so I'll close this one

**Comment by jasperblues** [comment]
It was actually the 3rd one, Aleksey also logged it :) 

Yep, let's put implementation suggestions on the remaining open one.
