### ISSUE TITLE
Support named parameters. 

### ISSUE THREAD

**Issue by jasperblues** [liberation-data/drivine#5]
Comes out-of-box on Neo4j. On Postgres/Agens these need to be faked - transform to ordered params.

**Comment by jasperblues** [comment]
Fixed in 2.0.6

**Comment by ElePhontitis** [comment]
@jasperblues maybe it would be good to mention the different types of parameters (ordered and named) in the documentation. The cyphers in the docs are often injected and remain hidden to the reader. For example I was initially trying to bind `{name: $name}` with `.bind([dto.name])` and had to check the example repo to find out that `bind({name: dto.name})` was the right way.

**Comment by jasperblues** [comment]
Thank you for the suggestion @ElePhontitis, it is good to know. 

There is a lot of documentation required, and I'm juggling doing that between new features (current one in flight is RedisGraph support) and client work. 

Therefore, I will happily take a pull request, no matter how sparse, that documents your discoveries for others. Contributors are (welcome to be) featured on the website. 

The guide is just a set of markdown.md files in the `docs/guide` directory.
