### ISSUE TITLE
Why is it important to add @liberation-data/agensgraph is I am using neo4j

### ISSUE THREAD

**Issue by Quadriphobs1** [liberation-data/drivine#56]

**Comment by xv-jasper-b** [comment]
Duplicate of #30 

Please follow this issue @Quadriphobs1. Contributions welcome.

**Comment by jasperblues** [comment]
Duplicate of #30

Please follow this issue @Quadriphobs1. Contributions welcome.

**Comment by Quadriphobs1** [comment]
I have actually switched over to using bride since it's an important part of my day... But maybe I'll take a look into it at a leisure time the API for this is actually better than neode for me

**Comment by jasperblues** [comment]
You are very welcome to do that. Thank you @Quadriphobs1
