### ISSUE TITLE
Use with Neo4j version <= 4.0.0

### ISSUE THREAD

**Issue by anrolmar** [liberation-data/drivine#61]
Hi. I'm trying to use drivine with neo4j 3.8.X and when I'm trying to access the database, I get the next error:

`[ WARN  ] [2020-10-29T09:27:07.094Z] [Neo4jConnection] Closing session with error: Error: Driver is connected to the database that does not support multiple databases. Please upgrade to neo4j 4.0.0 or later in order to use this functionality`

Do you know if there is an option in the Drivine Options to disallow this functionality?

Thanks

**Comment by jasperblues** [comment]
Are you bootstrapping from a `.env` file like this? 

```
DATABASE_TYPE=NEO4J
DATABASE_USER='neo4j'
DATABASE_PASSWORD='h4ckM3'
DATABASE_HOST='localhost'
DATABASE_PORT=7687
DATABASE_NAME='neo4j'
```

It should work if you remove the `DATABASE_NAME` property, so that it is: 

```
```
DATABASE_TYPE=NEO4J
DATABASE_USER='neo4j'
DATABASE_PASSWORD='h4ckM3'
DATABASE_HOST='localhost'
DATABASE_PORT=7687
```

Can you please confirm it works? If not then let us investigate further.

**Comment by anrolmar** [comment]
It works.

Thank you, very much

**Comment by jasperblues** [comment]
You are welcome @anrolmar !
