### ISSUE TITLE
.cypher files missing after transpilation

### ISSUE THREAD

**Issue by anrolmar** [liberation-data/drivine#62]
After the build step, there are no .cypher files in the dist directory. That is because of `tsc` behaviour to only include ts/js files. How did you manage to get it to work?

```
Cannot find module '/****/api/dist/user/repository/userById.cypher'
Require stack:

/****/api/node_modules/@liberation-data/drivine/DrivineInjectionDecorators.js
```

**Comment by jasperblues** [comment]
Please follow #34 @anrolmar. Meanwhile, here is a [work-around](https://github.com/liberation-data/drivine-inspiration/issues/8#issuecomment-717594694). 

## Workaround 

I will provide an official solution soon, in the meantime can you please write your queries inline (in the code)? For example: 

```typescript
const spec = new QuerySpecification(`MATCH (n) return (n)`)
```
 
Alternatively, you might modify your build/watch script to copy those files over. If using watch it could be a bit tricky, but might look something like: 

*Package.json:* 
```
"watch-dev": "rimraf dist && cross-env NODE_ENV=development ./node_modules/.bin/tsc-watch --onSuccess \"copyCpyherFiles.sh""
```

. . where `copyCypherFiles.sh` is an exercise for the reader at this point.

**Comment by anrolmar** [comment]
Thank you very much. But I think it would be a great feature to include.

**Comment by jasperblues** [comment]
Yes @anrolmar it is high priority. Features most asked for (not formally measured): 

#34 : This issue. 
#32 : Clear guides to use without Nest JS. (and NestJS pulled in as optional npm addon). 
#36 : Don't pull in other platform's driver. 

Currently working on RedisGraph Support, in between a lot of client work. Will happily take PRs, documentation or any other help large or small (including logging issues and sharing feedback 👍 ).
