### ISSUE TITLE
Automatically handle saving Date Javascript Object

### ISSUE THREAD

**Issue by brvnonascimento** [liberation-data/drivine#68]
Would be nice to have a default behavior for such a common use case following the principle of convention over configuration. 

It took me a while to figure out that the problem of my Save repository method were the properties with the Date constructor. I'm using Neo4j for the record.

You rock, Jasper!

**Comment by brvnonascimento** [comment]
I would happily make a pull request! It would be nice to know which timestamp standard should be the default (ISO 8601?).

**Comment by jasperblues** [comment]
That's awesome @brvnonascimento, thank you for contributing! 

I think 8601 makes the best default. Perhaps we can add support for epoch/unix style and others later.

**Comment by jasperblues** [comment]
I'm adding this feature now (as I need it myself)

**Comment by jasperblues** [comment]
Added this in 2.8.0

When coming from Neo4j, DateTime and Date automatically are marshalled to native Date. This is now default behavior, if someone needs it to be optional let me know. 

When going to Neo4j use ObjectUtils.primitiveProps with default options, like [this](https://github.com/liberation-data/drivine/blob/master/test/2.Integration/EmployeeRepository.ts)

**Comment by Bastianowicz** [comment]
Was a breaking change though even if the semver does not tell. Took me some time to figure this out. I was going crazy since what I wrote was not what I received :D

**Comment by jasperblues** [comment]
Any example of what you needed to change @Bastianowicz  ? _(So I can understand code patterns)_. 

Do you need a switch to turn this feature on/off?

**Comment by Bastianowicz** [comment]
Nah I use the library to persist and rehydrate entities. Since the entity had an neo4j date time I formerly converted the JS Date objects into neo4j on save and vice versa. I was wondering why that mechanism broke after the update. The conversion of course stopped working since I suddenly received real JS Date objects. 
This enhances my code so I like the change but it struck me by surprise

**Comment by jasperblues** [comment]
Noted, will try to be more careful of that next time.

**Comment by Bastianowicz** [comment]
Really nevermind 😊 I am happy with the change and the library.
