### ISSUE TITLE
@nestjs/common@">= 6 <= 7" from @liberation-data/drivine@2.2.1

### ISSUE THREAD

**Issue by jclappiway** [liberation-data/drivine#84]
current version is : @nestjs/common@8.2.4
can you bump this peer dependency to 8.x ?

**Comment by jasperblues** [comment]
Really swamped with my day-job work and catching after a week out with COVID. Are you able to send a PR @jclappiway ? I will push it up to npm straight away.

**Comment by jasperblues** [comment]
Here's the new version https://www.npmjs.com/package/@liberation-data/drivine
