### ISSUE TITLE
Use Transactions in Tests

### ISSUE THREAD

**Issue by Bastianowicz** [liberation-data/drivine#93]
I am wondering is it possible to start a transaction in jest.beforeEach und roll it back in jest.afterEach in end2end tests? I tried some things but don't seem to get it to work. I have a few ideas what might be the matter but maybe you have already tried something like that.

The following aproach does not break the tests but also does not rollback the changes.

```typescript
describe("e2e testcase", () => {
    let app: INestApplication;
    let connection: Connection;
    beforeAll(async () => {
        app = await initializeAppWithValidAuth(); // basically does Test.createTestingModule and some authentification mocking
        connection = await app.get(DrivineModule).registry.connectionProvider().connect();

    });
    beforeEach(async ()=>{
        await connection.startTransaction();
    });
    afterEach(async ()=>{
        await connection.rollbackTransaction();
    });

// ...
```

**Comment by Bastianowicz** [comment]
RTFM! https://docs.nestjs.com/fundamentals/testing
Unfortunately it does not work either. Changes are being applied and persisted in neo4j. Any idea what I could possibly do wrong?

**Comment by jasperblues** [comment]
Have you tried the sample app @Bastianowicz ? 

From memory I don't think you can expect a transaction that's is started in a test to work with HTTP endpoints. (Although you could probably find a way to make it work). 

The idea is to integration test your transactional services. Controller should be just a protocol adapter to call your services.

**Comment by Bastianowicz** [comment]
Using the controller directly did work as expected. Thank you. I think I am leaving the infrastructure layer out here and just test the integration from controller to neo4j. Thanks a lot.
